(define (open-input-file path) (open-input-file/k path raise-io-error values))
(define (open-input-file/k path kf k)
  (open-file-istream/k path kf (lambda (s) (k (istream->iport s)))))
(define (open-output-file path restriction)
  (open-output-file/k path restriction raise-io-error values))
(define (open-output-file/k path restriction kf k)
  (open-file-ostream/k path restriction kf (lambda (s) (k (ostream->oport s)))))

(define (open-file-istream path) (open-file-istream/k path raise-io-error values))
(define (open-file-ostream path restriction)
  (open-file-ostream/k path restriction raise-io-error values))
(define (directory-file*       path) (directory-file*/k       path raise-io-error values))
(define (make-symbolic-link to path) (make-symbolic-link/k to path raise-io-error values))
(define (make-directory        path) (make-directory/k        path raise-io-error values))
(define (move-file          old new) (move-file/k          old new raise-io-error values))
(define (delete-file           path) (delete-file/k           path raise-io-error values))
(define (delete-directory      path) (delete-directory/k      path raise-io-error values))
(define (file-type             path) (file-type/k             path raise-io-error values))
(define (file-size             path) (file-size/k             path raise-io-error values))
(define (file-permissions      path) (file-permissions/k      path raise-io-error values))
(define (file-modified-seconds path) (file-modified-seconds/k path raise-io-error values))
(define (set-file-permissions! path permissions)
  (set-file-permissions!/k path permissions raise-io-error values))
(define (set-file-modified-seconds! path seconds)
  (set-file-modified-seconds!/k path seconds raise-io-error values))

(define (host-process-in            p) (p 'in))
(define (host-process-out           p) (p 'out))
(define (host-process-err           p) (p 'err))
(define (host-process-exit-code     p) (p 'exit-code))
(define (host-process-pid           p) (p 'pid))
(define (host-process-wait          p) (p 'wait))
(define (host-process-kill          p) (p 'kill))
(define (host-process-interrupt     p) (p 'interrupt))
(define (host-process-process/group p) (p 'process/group))
