(define (make-posix-table argument* environment raw-process/k filesystem network set-signal-handler! exit)
  (make-platform-table argument* environment raw-process/k filesystem network set-signal-handler! exit))
(define posix-table-argument*           (make-platform-table-field 0))
(define posix-table-environment         (make-platform-table-field 1))
(define posix-table-raw-process/k       (make-platform-table-field 2))
(define posix-table-filesystem          (make-platform-table-field 3))
(define posix-table-network             (make-platform-table-field 4))
(define posix-table-set-signal-handler! (make-platform-table-field 5))
(define posix-table-exit                (make-platform-table-field 6))
(define posix-table.default
  (make-posix-table
    '() '()
    (lambda (in out err path arg* env kf k)
      (kf 'unsupported (list (vector '(unsupported posix-raw-process/k) path arg*))))
    (lambda (method . arg*)
      (lambda (kf k)
        (kf 'unsupported (list (vector '(unsupported posix-filesystem) method arg*)))))
    (lambda (method . arg*)
      (lambda (kf k)
        (kf 'unsupported (list (vector '(unsupported posix-network) method arg*)))))
    (lambda (signal handler) (values))
    (lambda (exit-code) (values))))

(define platform-posix                    (make-platform-field 'posix posix-table.default))
(define current-posix-argument*           (current-platform-field-parameter platform-posix posix-table-argument*))
(define current-posix-environment         (current-platform-field-parameter platform-posix posix-table-environment))
(define current-posix-raw-process/k       (current-platform-field-parameter platform-posix posix-table-raw-process/k))
(define current-posix-filesystem          (current-platform-field-parameter platform-posix posix-table-filesystem))
(define current-posix-network             (current-platform-field-parameter platform-posix posix-table-network))
(define current-posix-set-signal-handler! (current-platform-field-parameter platform-posix posix-table-set-signal-handler!))
(define current-posix-exit                (current-platform-field-parameter platform-posix posix-table-exit))
