;; racket bootstrap/run-file.rkt src/run-cli.scm test/lll.scm
(include "../src/compiler/lll.scm")
(include "../src/compiler/lll-c.scm")
(include "../src/compiler/lll-x86-64.scm")

(let ((P '(begin
            (set! rax 55)
            (begin
              (set! rdx 11)
              (set! rax (+ rax 7)))
            (set! rax (* rax rdx))
            (begin
              (set! r10 #x1000)
              (set! r11 16)
              (set! (memory 8 r10) rax)
              (set! (memory 8 (+ r10 8)) rdx)
              (set! (memory 8 (+ r10 r11)) rdx)
              (set! (memory 8 (+ r10 r11)) rdx)
              (set! rax (memory 8 (+ r10 8)))
              (set! rdx (memory 8 r10))
              (set! rax (* rax 2))
              (set! rdx (* rdx 2))
              (set! rdi (memory 8 (+ r10 r11)))
              (set! rsi (memory 8 (+ r10 r11)))))))
  (displayln "LLL:")
  (pretty-write P)
  (LLL-validate P)
  (displayln "==>")
  (writeln (LLL-eval P '()))
  (newline)
  (displayln "LLL C:")
  (LLL-validate-C P)
  (LLL-emit-C P)
  (newline)
  (displayln "LLL x86-64:")
  (LLL-validate-x86-64 P)
  (LLL-emit-x86-64-at&t P))
