;;;;;;;;;;;
;;; HLL ;;;
;;;;;;;;;;;
;; Expr               ::= #(ref          Note Var)
;;                      | #(primop       Note <primop>)
;;                      | #(quote        Note <value>)
;;                      | #(if           Note Expr Expr Expr)
;;                      | #(begin        Note Expr^ Expr)
;;                      | #(call         Note Expr (Expr ...))
;;                      | #(case-lambda  Note (Case-lambda-clause ...)
;;                      | #(letrec       Note (Let-binding ...) Expr)
;;                      | #(let*         Note (Let-binding ...) Expr)
;;                      | #(apply        Note Expr (Expr ...) Expr)
;;                      | #(apply/values Note Expr Expr)
;;                      | #(case-values  Note Expr (Case-lambda-clause ...))
;;                      | #(values       Note (Expr ...))
;;                      | #(dynamic-ref  Note Expr)
;;                      | #(dynamic-push Note Expr Expr Expr)
;; Case-lambda-clause ::= (Param*~ . Expr)
;; Let-binding        ::= (Param . Expr)
;; Expr^              ::= Expr | (Expr^ . Expr^)
;; Param*~            ::= Param | (Param ...) | (Param Param ... . Param)
;; Param              ::= Var | #f
;; Var                ::= <uvar>
;; Note               ::= <value>
(define (HLL-validate P)
  (define (list?! x) (or (list? x) (mistake "not a list" x)))
  (define (Var? x) (uvar? x))
  (define (Param? x) (or (not x) (Var? x)))
  (define (Param?!/ctx ctx x) (or (Param? x) (mistake "not a Param" x ctx)))
  (define (Param*?!/ctx ctx x)
    (or (Param? x) (null? x)
        (and (pair? x) (Param?!/ctx ctx (car x)) (Param*?!/ctx ctx (cdr x)))
        (mistake "not a parameter list" x ctx)))
  (define (Let-binding*?!/ctx ctx x*)
    (list?! x*)
    (andmap (lambda (x)
              (unless (let-binding? x)
                (mistake "not a let binding" x ctx))
              (let ((p (let-binding-lhs x)) (e (let-binding-rhs x)))
                (and (Param*?!/ctx ctx p) (Expr?!/ctx ctx e))))
            x*))
  (define (Case-lambda-clause*?!/ctx ctx x*)
    (list?! x*)
    (andmap (lambda (x)
              (unless (cl-clause? x)
                (mistake "not a case-lambda clause" x ctx))
              (let ((p (cl-clause-param x)) (e (cl-clause-body x)))
                (and (Param*?!/ctx ctx p) (Expr?!/ctx ctx e))))
            x*))
  (define (Expr?!/ctx ctx x)
    (define (fail) (mistake "not an Expr" x ctx))
    (if (vector? x)
        (let ((len (vector-length x)))
          (if (<= 2 len)
              (let ((tag (vector-ref x 0)) (note (vector-ref x 1)))
                (case len
                  ((3) ((case tag
                          ((ref)    (lambda (v) (or (Var? v) (mistake "not a Var" v ctx))))
                          ((primop) (lambda (p) (or (primop? p) (mistake "not a primop" p ctx))))
                          ((quote)  (lambda (val) #t))
                          ((case-lambda) (lambda (clc*) (Case-lambda-clause*?!/ctx x clc*)))
                          ((values) (lambda (rand*) (Expr*?!/ctx x rand*)))
                          ((dynamic-ref) (lambda (key) (Expr?!/ctx x key)))
                          (else (fail)))
                        (vector-ref x 2)))
                  ((4) ((case tag
                          ((call)   (lambda (rator rand*)
                                      (and (Expr?!/ctx x rator) (Expr*?!/ctx x rand*))))
                          ((letrec) (lambda (lb* body)
                                      (and (Let-binding*?!/ctx ctx lb*) (Expr?!/ctx x body))))
                          ((let*)   (lambda (lb* body)
                                      (and (Let-binding*?!/ctx ctx lb*) (Expr?!/ctx x body))))
                          ((begin)  (lambda (e^ e) (Expr^?!/ctx x e^) (Expr?!/ctx x e)))
                          ((apply/values)
                           (lambda (rator rand) (and (Expr?!/ctx x rator) (Expr?!/ctx x rand))))
                          ((case-values)
                           (lambda (rand clc*)
                             (and (Expr?!/ctx x rand) (Case-lambda-clause*?!/ctx x clc*))))
                          (else (fail)))
                        (vector-ref x 2) (vector-ref x 3)))
                  ((5) ((case tag
                          ((if) (lambda (c t f)
                                  (and (Expr?!/ctx x c) (Expr?!/ctx x t) (Expr?!/ctx x f))))
                          ((apply)
                           (lambda (rator rand* lrand)
                             (and (Expr?!/ctx x rator) (Expr*?!/ctx x rand*) (Expr?!/ctx x lrand))))
                          ((dynamic-push)
                           (lambda (key value body)
                             (and (Expr?!/ctx x key) (Expr?!/ctx x value) (Expr?!/ctx x body))))
                          (else (fail)))
                        (vector-ref x 2) (vector-ref x 3) (vector-ref x 4)))
                  (else (fail))))
              (fail)))
        (begin (mistake "really" x ctx) (fail))))
  (define (Expr*?!/ctx ctx x*) (list?! x*) (andmap (lambda (x) (Expr?!/ctx ctx x)) x*))
  (define (Expr^?!/ctx ctx x^) (tree-andmap (lambda (x) (Expr?!/ctx ctx x)) x^))
  (Expr?!/ctx #f P))

(define (HLL:ref          note var)               (vector 'ref          note var))
(define (HLL:primop       note p)                 (vector 'primop       note p))
(define (HLL:quote        note val)               (vector 'quote        note val))
(define (HLL:if           note c t f)             (vector 'if           note c t f))
(define (HLL:begin        note e^ e)              (vector 'begin        note e^ e))
(define (HLL:call         note rator rand*)       (vector 'call         note rator rand*))
(define (HLL:case-lambda  note clc*)              (vector 'case-lambda  note clc*))
(define (HLL:letrec       note lb* body)          (vector 'letrec       note lb* body))
(define (HLL:let*         note lb* body)          (vector 'let*         note lb* body))
(define (HLL:apply        note rator rand* lrand) (vector 'apply        note rator rand* lrand))
(define (HLL:apply/values note rator rand)        (vector 'apply/values note rator rand))
(define (HLL:case-values  note rand clc*)         (vector 'case-values  note rand clc*))
(define (HLL:values       note rand*)             (vector 'values       note rand*))
(define (HLL:dynamic-ref  note key)               (vector 'dynamic-ref  note key))
(define (HLL:dynamic-push note key value body)    (vector 'dynamic-ref  note key value body))
(define (cl-clause? x)      (pair? x))
(define (cl-clause p e)     (cons p e))
(define (cl-clause-param c) (car c))
(define (cl-clause-body  c) (cdr c))
(define (let-binding? x)    (pair? x))
(define (let-binding p e)   (cons p e))
(define (let-binding-lhs b) (car b))
(define (let-binding-rhs b) (cdr b))

(define (clc*-map f c*) (map (lambda (c) (f (cl-clause-param c) (cl-clause-body c))) c*))
(define (lb*-map f lb*) (map (lambda (lb) (f (let-binding-lhs lb) (let-binding-rhs lb))) lb*))

(define (HLL-pretty P)
  (define (param-pretty x) (if x (uvar->symbol x) #f))
  (define (lb*-pretty lb*) (map (lambda (lb) (list (param-pretty (let-binding-lhs lb))
                                                   (loop (let-binding-rhs lb))))
                                lb*))
  (define (clc*-pretty clc*) (map (lambda (clc) (list (improper-list-map param-pretty
                                                                         (cl-clause-param clc))
                                                      (loop (cl-clause-body clc))))
                                  clc*))
  (define (loop x)
    (let ((len (vector-length x)) (tag (vector-ref x 0)) (note (vector-ref x 1)))
      (case len
        ((3) ((case tag
                ((ref)         (lambda (v) (list 'ref (param-pretty v))))
                ((primop)      (lambda (p) (list 'primop (primop-name p))))
                ((quote)       (lambda (val) (list 'quote val)))
                ((case-lambda) (lambda (clc*) (cons 'case-lambda (clc*-pretty clc*))))
                ((values)      (lambda (rand*) (cons 'values (map loop rand*))))
                ((dynamic-ref) (lambda (key) (list 'dynamic-ref (loop key)))))
              (vector-ref x 2)))
        ((4) ((case tag
                ((call)   (lambda (rator rand*) (cons* 'call (loop rator) (map loop rand*))))
                ((letrec) (lambda (lb* body) (list 'letrec (lb*-pretty lb*) (loop body))))
                ((let*)   (lambda (lb* body) (list 'let*   (lb*-pretty lb*) (loop body))))
                ((begin)  (lambda (e^ e) (cons 'begin (tree-map-flatten loop e^ (loop e)))))
                ((apply/values) (lambda (rator rand) (list 'apply/values (loop rator) (loop rand))))
                ((case-values) (lambda (rand clc*)
                                 (cons* 'case-values (loop rand) (clc*-pretty clc*)))))
              (vector-ref x 2) (vector-ref x 3)))
        ((5) ((case tag
                ((if) (lambda (c t f) (list 'if (loop c) (loop t) (loop f))))
                ((apply) (lambda (rator rand* lrand)
                           (cons* 'apply (loop rator) (append (map loop rand*) (loop lrand)))))
                ((dynamic-push) (lambda (key value body)
                                  (list 'dynamic-push (loop key) (loop value) (loop body)))))
              (vector-ref x 2) (vector-ref x 3) (vector-ref x 4))))))
  (loop P))

(define (HLL-map-quote P f)
  (define (Let-binding* lb*) (lb*-map (lambda (lhs rhs) (let-binding lhs (Expr rhs))) lb*))
  (define (CL-clause* clc*) (clc*-map (lambda (param body) (cl-clause param (Expr body))) clc*))
  (define (Expr x)
    (let ((len (vector-length x)) (tag (vector-ref x 0)) (note (vector-ref x 1)))
      (case len
        ((3) ((case tag
                ((ref primop)  (lambda (_) x))
                ((quote)       (lambda (v) (f x note v)))
                ((case-lambda) (lambda (clc*) (HLL:case-lambda note (CL-clause* clc*))))
                ((values)      (lambda (rand*) (HLL:values note (map Expr rand*))))
                ((dynamic-ref) (lambda (key) (HLL:dynamic-ref note (Expr key)))))
              (vector-ref x 2)))
        ((4) ((case tag
                ((call)   (lambda (rator rand*) (HLL:call note (Expr rator) (map Expr rand*))))
                ((letrec) (lambda (lb* body) (HLL:letrec note (Let-binding* lb*) (Expr body))))
                ((let*)   (lambda (lb* body) (HLL:let*   note (Let-binding* lb*) (Expr body))))
                ((begin)  (lambda (e^ e) (HLL:begin note (tree-map Expr e^) (Expr e))))
                ((apply/values)
                 (lambda (rator rand) (HLL:apply/values note (Expr rator) (Expr rand))))
                ((case-values)
                 (lambda (rand clc*) (HLL:case-values note (Expr rand) (CL-clause* clc*)))))
              (vector-ref x 2) (vector-ref x 3)))
        ((5) ((case tag
                ((if) (lambda (c t f) (HLL:if note (Expr c) (Expr t) (Expr f))))
                ((apply) (lambda (rator rand* lrand)
                           (HLL:apply note (Expr rator) (map Expr rand*) (Expr lrand))))
                ((dynamic-push) (lambda (key value body)
                                  (HLL:dynamic-push note (Expr key) (Expr value) (Expr body)))))
              (vector-ref x 2) (vector-ref x 3) (vector-ref x 4))))))
  (Expr P))

(define (HLL-normalize-quote P proc=>primop)
  (mdefine lb* '())
  (define (proc->primop proc note) (let ((pp (assv proc proc=>primop)))
                                     (if pp (HLL:primop note (cdr pp)) (HLL:quote note proc))))
  (define p.cons   (proc->primop cons #f))
  (define p.vector (proc->primop vector #f))
  (let ((x (HLL-map-quote
             P (lambda (x note v)
                 (let loop/note ((v v) (note note))
                   (define (loop v) (loop/note v #f))
                   (cond ((immediate? v) (HLL:quote note v))
                         ((procedure? v) (proc->primop v note))
                         (else (let ((t (uvar #f))
                                     (x (cond ((pair? v) (HLL:call p.cons #f (list (loop (car v))
                                                                                   (loop (cdr v)))))
                                              ((vector? v) (HLL:call p.vector #f
                                                                     (map loop (vector->list v))))
                                              (else (HLL:quote #f v)))))
                                 (set! lb* (cons (let-binding t x) lb*))
                                 (HLL:ref note t)))))))))
    (if (null? lb*) x (HLL:let* #f lb* x))))

;; Alternative to HLL-normalize-quote when we do not want to simplify quote
(define (HLL-normalize-primop P proc=>primop)
  (HLL-map-quote P (lambda (x note v) (let ((pp (and (procedure? v) (assv v proc=>primop))))
                                        (if pp (HLL:primop note (cdr pp)) x)))))
