;;; HLL includes `let*`, `apply/values`, and `case-values` to reduce closure allocation.
;;; HLL includes `late` to support transformations that defer decisions.
;;;;;;;;;;;
;;; HLL ;;;
;;;;;;;;;;;
;; Expr               ::= #(ref          Note Var)
;;                      | #(primop       Note <primop>)
;;                      | #(quote        Note <value>)
;;                      | #(if           Note Expr Expr Expr)
;;                      | #(begin        Note Expr^ Expr)
;;                      | #(call         Note Expr (Expr ...))
;;                      | #(case-lambda  Note (Case-lambda-clause ...)
;;                      | #(letrec       Note (Let-binding ...) Expr)
;;                      | #(let*         Note (Let-binding ...) Expr)
;;                      | #(apply/values Note Expr Expr)
;;                      | #(case-values  Note Expr (Case-lambda-clause ...))
;;                      | #(late         Note &Expr)
;; Case-lambda-clause ::= #(Arity Param*~ Expr)
;; Arity              ::= <integer>  ; complemented (negative) if arity is variadic
;; Let-binding        ::= (Param . Expr)
;; &Expr              ::= <box that eventually contains an Expr>
;; Expr^              ::= Expr | (Expr^ . Expr^)
;; Param*~            ::= Param | (Param ...) | (Param Param ... . Param)
;; Param              ::= Var | #f
;; Var                ::= <hllvar>
;; Note               ::= <value>
(define (HLL:ref          note var)         (vector 'ref          note var))
(define (HLL:primop       note p)           (vector 'primop       note p))
(define (HLL:quote        note val)         (vector 'quote        note val))
(define (HLL:if           note c t f)       (vector 'if           note c t f))
(define (HLL:begin        note e^ e)        (vector 'begin        note e^ e))
(define (HLL:call         note rator rand*) (vector 'call         note rator rand*))
(define (HLL:case-lambda  note clc*)        (vector 'case-lambda  note clc*))
(define (HLL:letrec       note lb* body)    (vector 'letrec       note lb* body))
(define (HLL:let*         note lb* body)    (vector 'let*         note lb* body))
(define (HLL:apply/values note rator rand)  (vector 'apply/values note rator rand))
(define (HLL:case-values  note rand clc*)   (vector 'case-values  note rand clc*))
(define (HLL:late         note &e)          (vector 'late         note &e))
(define (HLL-note x)        (vector-ref x 1))
(define (cl-clause? x)      (and (vector? x) (= (vector-length x) 3)))
(define (cl-clause a p e)   (vector a p e))
(define (cl-clause-arity c) (vector-ref c 0))
(define (cl-clause-param c) (vector-ref c 1))
(define (cl-clause-body  c) (vector-ref c 2))
(define (let-binding? x)    (pair? x))
(define (let-binding p e)   (cons p e))
(define (let-binding-lhs b) (car b))
(define (let-binding-rhs b) (cdr b))

(define-record-type (lambda (v) (list 'hllvar (hllvar-name v))) make-hllvar hllvar?
  (hllvar-name     set-hllvar-name!)
  (hllvar-source   set-hllvar-source!)
  (hllvar-data     set-hllvar-data!)
  (hllvar-refcount set-hllvar-refcount!))
(define (hllvar name source) (make-hllvar name source #f 0))
(define (hllvar-copy x)
  (make-hllvar (hllvar-name x) (hllvar-source x) (hllvar-data x) (hllvar-refcount x)))
(define (add-hllvar-refcount!    x c) (set-hllvar-refcount! x (+ (hllvar-refcount x) c)))
(define (inc-hllvar-refcount!    x)   (add-hllvar-refcount! x 1))
(define (hllvar-referenced?      x)   (< 0 (hllvar-refcount x)))
(define (hllvar-referenced-once? x)   (= 1 (hllvar-refcount x)))

(define ($cl-clause p e) (cl-clause 0 p e))  ; NOTE: HLL-initialize will compute correct arity
(define (param->arity p) (let loop ((p p) (a 0)) (cond ((null? p) a)
                                                       ((pair? p) (loop (cdr p) (+ a 1)))
                                                       (else      (- (+ a 1))))))
(define (arity->arity-mask arity) (if (< arity 0)
                                      (bitwise-asl -1 (bitwise-not arity))
                                      (bitwise-asl 1 arity)))
(define (arity-mask-add mask arity) (bitwise-ior (arity->arity-mask arity) mask))
(define (clc*-simplify clc*)
  (let loop ((clc* clc*) (mask 0))
    (if (null? clc*)
        '()
        (let ((clc (car clc*)) (clc* (cdr clc*)))
          (let ((new-mask (arity-mask-add mask (cl-clause-arity clc))))
            (if (= mask new-mask)
                (loop clc* mask)
                (cons clc (loop clc* new-mask))))))))
(define (clc*-sort clc*)  ; NOTE: only valid after clc* has been simplified
  (let loop ((clc* clc*) (fixed* '()) (variadic* '()))
    (if (null? clc*)
        (append fixed* variadic*)
        (let ((clc (car clc*)) (clc* (cdr clc*)))
          (let ((arity (cl-clause-arity clc)))
            (if (< arity 0)
                (loop clc* fixed* (cons clc variadic*))
                (loop clc* (let insert ((fixed* fixed*))
                             (if (null? fixed*)
                                 (list clc)
                                 (let ((next (car fixed*)))
                                   (if (<= arity (cl-clause-arity next))
                                       (cons clc fixed*)
                                       (cons next (insert (cdr fixed*)))))))
                      variadic*)))))))
(define (clc*-ref/k clc* argc kfail k)
  (let loop ((clc* clc*))
    (if (null? clc*)
        (kfail)
        (let ((clc (car clc*)) (clc* (cdr clc*)))
          (let ((arity (cl-clause-arity clc)))
            (if (or (= arity argc) (and (< arity 0) (<= (bitwise-not arity) argc)))
                (k clc)
                (loop clc*)))))))
(define (param-for-each f p)
  (let loop ((p p)) (cond ((hllvar? p) (f p))
                          ((pair? p)   (let ((x (car p))) (when (hllvar? x) (f x)))
                                       (loop (cdr p)))
                          (else        (values)))))
(define (clc*-map f c*)
  (map (lambda (c) (f (cl-clause-arity c) (cl-clause-param c) (cl-clause-body c))) c*))
(define (clc*-for-each f c*)
  (for-each (lambda (c) (f (cl-clause-arity c) (cl-clause-param c) (cl-clause-body c))) c*))
(define (lb*-map f lb*) (map (lambda (lb) (f (let-binding-lhs lb) (let-binding-rhs lb))) lb*))
(define (lb*-for-each f lb*)
  (for-each (lambda (lb) (f (let-binding-lhs lb) (let-binding-rhs lb))) lb*))

(splicing-let
  ((p.apply        (HLL:primop #f (procedure->primop apply)))
   (p.values       (HLL:primop #f (procedure->primop values)))
   (p.panic        (HLL:primop #f (procedure->primop panic)))
   (p.make-mvector (HLL:primop #f (procedure->primop make-mvector)))
   (p.mvector-ref  (HLL:primop #f (procedure->primop mvector-ref)))
   (p.mvector-set! (HLL:primop #f (procedure->primop mvector-set!)))
   (p.cons         (HLL:primop #f (procedure->primop cons)))
   (e.0            (HLL:quote #f 0))
   (e.1            (HLL:quote #f 1)))
  (define (HLL:apply    note rand*) (HLL:call note p.apply rand*))
  (define (HLL:values   note rand*) (HLL:call note p.values rand*))
  (define (HLL:panic    note rand*) (HLL:call note p.panic rand*))
  (define (HLL:box      note val)   (HLL:call note p.make-mvector (list e.1 val)))
  (define (HLL:unbox    note b)     (HLL:call note p.mvector-ref  (list b e.0)))
  (define (HLL:set-box! note b val) (HLL:call note p.mvector-set! (list b e.0 val)))
  (define (HLL:cons     note a d)   (HLL:call note p.cons         (list a d)))
  (define (HLL:list     note rand*) (let loop ((note note) (rand* rand*))
                                      (if (null? rand*)
                                          (HLL:quote note '())
                                          (HLL:cons note (car rand*) (loop #f (cdr rand*)))))))

(splicing-local
  ((define-syntax HLL-case-build
     (syntax-rules (ref primop quote if begin call case-lambda letrec let* apply/values case-values
                        late)
       ((_ x (((ref a) . body) . clause*) v1* v2* v3*)
        (HLL-case-build x clause* ((ref . (lambda (a) . body)) . v1*) v2* v3*))
       ((_ x (((primop a) . body) . clause*) v1* v2* v3*)
        (HLL-case-build x clause* ((primop . (lambda (a) . body)) . v1*) v2* v3*))
       ((_ x (((quote a) . body) . clause*) v1* v2* v3*)
        (HLL-case-build x clause* ((quote . (lambda (a) . body)) . v1*) v2* v3*))
       ((_ x (((case-lambda a) . body) . clause*) v1* v2* v3*)
        (HLL-case-build x clause* ((case-lambda . (lambda (a) . body)) . v1*) v2* v3*))
       ((_ x (((late a) . body) . clause*) v1* v2* v3*)
        (HLL-case-build x clause* ((late . (lambda (a) . body)) . v1*) v2* v3*))
       ((_ x (((begin a b) . body) . clause*) v1* v2* v3*)
        (HLL-case-build x clause* v1* ((begin . (lambda (a b) . body)) . v2*) v3*))
       ((_ x (((call a b) . body) . clause*) v1* v2* v3*)
        (HLL-case-build x clause* v1* ((call . (lambda (a b) . body)) . v2*) v3*))
       ((_ x (((letrec a b) . body) . clause*) v1* v2* v3*)
        (HLL-case-build x clause* v1* ((letrec . (lambda (a b) . body)) . v2*) v3*))
       ((_ x (((let* a b) . body) . clause*) v1* v2* v3*)
        (HLL-case-build x clause* v1* ((let* . (lambda (a b) . body)) . v2*) v3*))
       ((_ x (((apply/values a b) . body) . clause*) v1* v2* v3*)
        (HLL-case-build x clause* v1* ((apply/values . (lambda (a b) . body)) . v2*) v3*))
       ((_ x (((case-values a b) . body) . clause*) v1* v2* v3*)
        (HLL-case-build x clause* v1* ((case-values . (lambda (a b) . body)) . v2*) v3*))
       ((_ x (((if a b c) . body) . clause*) v1* v2* v3*)
        (HLL-case-build x clause* v1* v2* ((if . (lambda (a b c) . body)) . v3*)))
       ((_ x (((wrong . a*) . body) . clause*) v1* v2* v3*)
        (HLL-case-unrecognized (wrong . a*)))
       ((_ x () v1* v2* v3*)
        (let ((default (lambda (y) (mistake "no matching HLL-case pattern for expression" y))))
          (HLL-case-finish x default v1* v2* v3*)))
       ((_ x ((y . body)) v1* v2* v3*) (let ((default (lambda (y) . body)))
                                         (HLL-case-finish x default v1* v2* v3*)))))
   (define-syntax (HLL-case-unrecognized stx)
     (syntax-case stx ()
       ((_ pattern) (mistake "invalid HLL-case pattern" (syntax->datum #'pattern)))))
   (define-syntax-rule
     (HLL-case-finish x default ((tag1 . handle1) ...) ((tag2 . handle2) ...) ((tag3 . handle3) ...))
     (case (vector-length x)
       ((3) ((case (vector-ref x 0) ((tag1) handle1) ... (else (lambda (_a) (default x))))
             (vector-ref x 2)))
       ((4) ((case (vector-ref x 0) ((tag2) handle2) ... (else (lambda (_a _b) (default x))))
             (vector-ref x 2) (vector-ref x 3)))
       ((5) ((case (vector-ref x 0) ((tag3) handle3) ... (else (lambda (_a _b _c) (default x))))
             (vector-ref x 2) (vector-ref x 3) (vector-ref x 4)))
       (else (default x)))))
  (define-syntax-rule (HLL-case e . clause*) (let ((x e)) (HLL-case-build x clause* () () ()))))

(splicing-local
  ((define-syntax Expr/note
     (syntax-rules (unquote /note ref primop quote if begin call case-lambda lambda letrec let*
                            apply/values case-values
                            apply values panic box unbox set-box! cons list)
       ((_ note ,x)                             x)
       ((_ note (ref ,v))                       (HLL:ref note v))
       ((_ note (primop ,p))                    (HLL:primop note p))
       ((_ note (quote ,v))                     (HLL:quote note v))
       ((_ note (quote v))                      (HLL:quote note 'v))
       ((_ note (if c t f))                     (HLL:if note (Expr c) (Expr t) (Expr f)))
       ((_ note (begin e))                      (Expr/note note e))
       ((_ note (begin e e* ...))               (Begin note (Expr e) ((Expr e*) ...)))
       ((_ note (call rator rand* ...))         (HLL:call note (Expr rator) (list (Expr rand*) ...)))
       ((_ note (letrec ,lb* body))             (HLL:letrec note lb* (Expr body)))
       ((_ note (let*   ,lb* body))             (HLL:let*   note lb* (Expr body)))
       ((_ note (letrec ((lhs rhs) ...) body))  (HLL:letrec note (list (let-binding lhs (Expr rhs)) ...) (Expr body)))
       ((_ note (let*   ((lhs rhs) ...) body))  (HLL:let*   note (list (let-binding lhs (Expr rhs)) ...) (Expr body)))
       ((_ note (letrec lb* e0 e1 . e*))        (Expr/note note (letrec lb* (begin e0 e1 . e*))))
       ((_ note (let*   lb* e0 e1 . e*))        (Expr/note note (let*   lb* (begin e0 e1 . e*))))
       ((_ note (case-lambda ,clc*))            (HLL:case-lambda note clc*))
       ((_ note (case-lambda (p*~ . body) ...)) (HLL:case-lambda note (list (CL-clause (Param*~ p*~) . body) ...)))
       ((_ note (lambda ,p*~ . body))           (HLL:case-lambda note (list (CL-clause p*~ . body))))
       ((_ note (lambda p*~ . body))            (HLL:case-lambda note (list (CL-clause (Param*~ p*~) . body))))
       ((_ note (apply/values rator rand))      (HLL:apply/values note (Expr rator) (Expr rand)))
       ((_ note (case-values rand ,clc*))       (HLL:case-values note (Expr rand) clc*))
       ((_ old (/note note e))                  (Expr/note note e))
       ((_ note (apply rand* ...))              (HLL:apply note (list (Expr rand*) ...)))
       ((_ note (values rand* ...))             (HLL:values note (list (Expr rand*) ...)))
       ((_ note (panic rand* ...))              (HLL:panic note (list (Expr rand*) ...)))
       ((_ note (box e))                        (HLL:box note (Expr e)))
       ((_ note (unbox b))                      (HLL:unbox note (Expr b)))
       ((_ note (set-box! b e))                 (HLL:set-box! note (Expr b) (Expr e)))
       ((_ note (cons a d))                     (HLL:cons note (Expr a) (Expr d)))
       ((_ note (list rand* ...))               (HLL:list note (list (Expr rand*) ...)))
       ((_ note (rator . rand*))                (HLL:-unrecognized (rator . rand*)))
       ((_ note stx)                            (Atom note stx))))
   (define-syntax CL-clause
     (syntax-rules ()
       ((_ p*~ e0 e1 . e*) (CL-clause p*~ (begin e0 e1 . e*)))
       ((_ p*~ body)       (let ((p p*~)) (cl-clause (param->arity p) p (Expr body))))))
   (define-syntax Param*~
     (syntax-rules ()
       ((_ ())        '())
       ((_ (p . p*~)) (cons p (Param*~ p*~)))
       ((_ p)         p)))
   (define-syntax Begin
     (syntax-rules ()
       ((_ note e^ (e))      (HLL:begin note e^ e))
       ((_ note e^ (e . e*)) (Begin note (cons e^ e) e*))))
   (define-syntax (Atom stx)
     (syntax-case stx ()
       ((_ note stx) (if (identifier? #'stx)
                         #'(HLL:ref note stx)
                         (let ((x (syntax-unwrap #'stx)))
                           (if (or (boolean? x) (number? x) (string? x))
                               #'(HLL:quote note stx)
                               (mistake "invalid HLL: form" #'stx)))))))
   (define-syntax (HLL:-unrecognized stx)
     (syntax-case stx ()
       ((_ e) (mistake "invalid HLL: form" (syntax->datum #'e)))))
   (define-syntax-rule (Expr e) (Expr/note #f e)))
  (define-syntax-rule (HLL: e) (Expr/note #f e)))

(define (HLL-pure? x)
  (HLL-case
    x
    ((ref _) #t) ((primop _) #t) ((quote _) #t) ((case-lambda _) #t)
    ((if c t f) (and (HLL-pure? c) (HLL-pure? t) (HLL-pure? f)))
    ;; TODO: some primop calls can also be #t
    (_ #f)))

(define (HLL-initialize P)
  (mdefine old* '())
  (define (restore-old*!) (for-each (lambda (v) (set-hllvar-data! v #f)) old*))
  (define (fail . x*) (restore-old*!) (apply mistake x*))
  (define (fresh/ctx ctx x)
    (when (hllvar-data x) (fail "Var is not unique" x ctx))
    (set! old* (cons x old*))
    (let ((new (hllvar (hllvar-name x) (hllvar-source x))))
      (set-hllvar-data! x new)
      new))
  (define (list?!/ctx ctx x) (unless (list? x) (fail "not a list" x ctx)))
  (define (Param/ctx ctx x) (cond ((not x) x)
                                  ((hllvar? x) (fresh/ctx ctx x))
                                  (else (fail "not a Param" x ctx))))
  (define (Param*~/ctx ctx y) (let loop ((x y))
                                (cond ((null? x) x)
                                      ((pair? x) (cons (Param/ctx ctx (car x)) (loop (cdr x))))
                                      (else (Param/ctx ctx x)))))
  (define (LB*/ctx ctx x*)
    (list?!/ctx ctx x*)
    (map (lambda (x) (let-binding (let-binding-lhs x) (Expr/ctx ctx (let-binding-rhs x))))
         (map (lambda (x)
                (unless (let-binding? x) (fail "not a let binding" x ctx))
                (let-binding (Param/ctx ctx (let-binding-lhs x)) (let-binding-rhs x)))
              x*)))
  (define (CLC*/ctx ctx x*)
    (list?!/ctx ctx x*)
    (map (lambda (x)
           (unless (cl-clause? x) (fail "not a case-lambda clause" x ctx))
           (let ((p (Param*~/ctx ctx (cl-clause-param x))))
             (cl-clause (param->arity p) p (Expr/ctx ctx (cl-clause-body x)))))
         x*))
  (define (Expr/ctx ctx x)
    (unless (and (vector? x) (< 0 (vector-length x))) (fail "invalid HLL" x ctx))
    (define note (HLL-note x))
    (HLL-case
      x
      ((ref v)                   (unless (hllvar? v) (fail "not a Var" v x ctx))
                                 (let ((new (hllvar-data v)))
                                   (unless (hllvar? new) (fail "unbound Var" v x ctx))
                                   (inc-hllvar-refcount! new)
                                   (HLL:ref note new)))
      ((primop p)                (unless (primop? p) (fail "not a primop" p x ctx)) x)
      ((quote val)               x)
      ((if c t f)                (HLL:if note (Expr/ctx x c) (Expr/ctx x t) (Expr/ctx x f)))
      ((begin e^ e)              (HLL:begin note (Expr^/ctx x e^) (Expr/ctx x e)))
      ((call rator rand*)        (HLL:call note (Expr/ctx x rator) (Expr*/ctx x rand*)))
      ((case-lambda clc*)        (HLL:case-lambda note (CLC*/ctx x clc*)))
      ((letrec lb* body)         (HLL:letrec note (LB*/ctx ctx lb*) (Expr/ctx x body)))
      ((let* lb* body)           (HLL:let*   note (LB*/ctx ctx lb*) (Expr/ctx x body)))
      ((apply/values rator rand) (HLL:apply/values note (Expr/ctx x rator) (Expr/ctx x rand)))
      ((case-values rand clc*)   (HLL:case-values note (Expr/ctx x rand) (CLC*/ctx x clc*)))
      ((late &e)                 (Expr/ctx ctx (unbox &e)))
      (x                         (fail "not an Expr" x ctx))))
  (define (Expr*/ctx ctx x*) (list?!/ctx ctx x*) (map (lambda (x) (Expr/ctx ctx x)) x*))
  (define (Expr^/ctx ctx x^) (tree-map (lambda (x) (Expr/ctx ctx x)) x^))
  (let ((P (Expr/ctx #f P)))
    (restore-old*!)
    P))

(define (HLL-refresh-refcount! P)
  (define (Param x) (when (hllvar? x) (set-hllvar-refcount! x 0)))
  (define (Param*~ x) (let loop ((x x))
                        (if (pair? x) (begin (Param (car x)) (loop (cdr x))) (Param x))))
  (define (LET* lb* body)
    (lb*-for-each (lambda (lhs _) (Param lhs)) lb*)
    (lb*-for-each (lambda (_ rhs) (Expr rhs)) lb*)
    (Expr body))
  (define (CLC* clc*) (clc*-for-each (lambda (a p body) (Param*~ p) (Expr body)) clc*))
  (define (Expr x)
    (define note (HLL-note x))
    (HLL-case
      x
      ((ref v)                   (inc-hllvar-refcount! v))
      ((primop _)                (values))
      ((quote v)                 (values))
      ((if c t f)                (Expr c) (Expr t) (Expr f))
      ((begin e^ e)              (tree-for-each Expr e^) (Expr e))
      ((call rator rand*)        (Expr rator) (for-each Expr rand*))
      ((case-lambda clc*)        (CLC* clc*))
      ((letrec lb* body)         (LET* lb* body))
      ((let* lb* body)           (LET* lb* body))
      ((apply/values rator rand) (Expr rator) (Expr rand))
      ((case-values rand clc*)   (Expr rand) (CLC* clc*))
      ((late &e)                 (Expr (unbox &e)))))
  (Expr P))

(define (HLL-copy P)
  (mdefine old* '())
  (define (fresh x)
    (set! old* (cons x old*))
    (let ((new (hllvar-copy x))) (set-hllvar-data! x new) new))
  (define (Param x) (if (hllvar? x) (fresh x) x))
  (define (Param*~ x) (let loop ((x x))
                        (if (pair? x) (cons (Param (car x)) (loop (cdr x))) (Param x))))
  (define (LB* lb*) (lb*-map (lambda (lhs rhs) (let-binding lhs (Expr rhs)))
                             (lb*-map (lambda (lhs rhs) (let-binding (Param lhs) rhs)) lb*)))
  (define (CLC* clc*)
    (clc*-map (lambda (arity p body) (cl-clause arity (Param*~ p) (Expr body))) clc*))
  (define (Expr x)
    (define note (HLL-note x))
    (HLL-case
      x
      ((ref v)                   (HLL:ref note (hllvar-data v)))
      ((primop _)                x)
      ((quote v)                 x)
      ((if c t f)                (HLL:if note (Expr c) (Expr t) (Expr f)))
      ((begin e^ e)              (HLL:begin note (tree-map Expr e^) (Expr e)))
      ((call rator rand*)        (HLL:call note (Expr rator) (map Expr rand*)))
      ((case-lambda clc*)        (HLL:case-lambda note (CLC* clc*)))
      ((letrec lb* body)         (HLL:letrec note (LB* lb*) (Expr body)))
      ((let* lb* body)           (HLL:let*   note (LB* lb*) (Expr body)))
      ((apply/values rator rand) (HLL:apply/values note (Expr rator) (Expr rand)))
      ((case-values rand clc*)   (HLL:case-values note (Expr rand) (CLC* clc*)))
      ((late &e)                 (Expr (unbox &e)))))
  (let ((P (Expr P)))
    (for-each (lambda (v) (set-hllvar-data! v (hllvar-data (hllvar-data v)))) old*)
    P))

(define (HLL-for-each-variable f P)
  (define (Param x) (when (hllvar? x) (f x)))
  (define (Param*~ x) (let loop ((x x))
                        (if (pair? x) (begin (Param (car x)) (loop (cdr x))) (Param x))))
  (define (LB* lb*) (lb*-for-each (lambda (lhs rhs) (Param lhs) (Expr rhs)) lb*))
  (define (CLC* clc*) (clc*-for-each (lambda (a p body) (Param*~ p) (Expr body)) clc*))
  (define (Expr x)
    (define note (HLL-note x))
    (HLL-case
      x
      ((ref _)                   (values))
      ((primop _)                (values))
      ((quote _)                 (values))
      ((if c t f)                (Expr c) (Expr t) (Expr f))
      ((begin e^ e)              (tree-for-each Expr e^) (Expr e))
      ((call rator rand*)        (Expr rator) (for-each Expr rand*))
      ((case-lambda clc*)        (CLC* clc*))
      ((letrec lb* body)         (LB* lb*) (Expr body))
      ((let* lb* body)           (LB* lb*) (Expr body))
      ((apply/values rator rand) (Expr rator) (Expr rand))
      ((case-values rand clc*)   (Expr rand) (CLC* clc*))
      ((late &e)                 (Expr (unbox &e)))))
  (Expr P))

(define (HLL-variable* P)
  (mdefine var* '())
  (HLL-for-each-variable (lambda (x) (set! var* (cons x var*))) P)
  var*)

(define (HLL-pretty P)
  (define (param-pretty x) (if x (hllvar-name x) #t))
  (define (lb*-pretty lb*) (map (lambda (lb) (list (param-pretty (let-binding-lhs lb))
                                                   (loop (let-binding-rhs lb))))
                                lb*))
  (define (clc*-pretty clc*) (map (lambda (clc) (list (improper-list-map param-pretty
                                                                         (cl-clause-param clc))
                                                      (loop (cl-clause-body clc))))
                                  clc*))
  (define (loop x)
    (HLL-case
      x
      ((ref v)                   (list 'ref (param-pretty v)))
      ((primop p)                (list 'primop (primop-name p)))
      ((quote val)               (list 'quote val))
      ((if c t f)                (list 'if (loop c) (loop t) (loop f)))
      ((begin e^ e)              (cons 'begin (tree-map-flatten loop e^ (list (loop e)))))
      ((call rator rand*)        (cons* 'call (loop rator) (map loop rand*)))
      ((case-lambda clc*)        (cons 'case-lambda (clc*-pretty clc*)))
      ((letrec lb* body)         (list 'letrec (lb*-pretty lb*) (loop body)))
      ((let* lb* body)           (list 'let*   (lb*-pretty lb*) (loop body)))
      ((apply/values rator rand) (list 'apply/values (loop rator) (loop rand)))
      ((case-values rand clc*)   (cons* 'case-values (loop rand) (clc*-pretty clc*)))
      ((late &e)                 (loop (unbox &e)))))
  (loop P))

(define (make-hllvar-rename!)
  (mlet ((uid 0))
    (lambda (x)
      (let ((uid.current uid))
        (set! uid (+ uid 1))
        (set-hllvar-name! x (string->symbol (string-append (symbol->string (or (hllvar-name x) '_))
                                                           "." (number->string uid.current))))))))

(define (HLL-distinguish-variable-names! P) (HLL-for-each-variable (make-hllvar-rename!) P))
(define (HLL-pretty-uid P)
  (let ((P (HLL-copy P))) (HLL-distinguish-variable-names! P) (HLL-pretty P)))

(define (HLL-check-letrec P)
  (mdefine var*.all '())
  (mdefine bnd*.pending '())
  (define (bind! v initialized? init-var)
    (let ((bnd (mvector initialized? init-var '())))
      (set-hllvar-data! v bnd)
      (set! bnd*.pending (cons bnd bnd*.pending)))
    (set! var*.all (cons v var*.all)))
  (define (bind-nonrec! v) (bind! v #t #f))
  (define (bind-rec!    v) (bind! v #f (hllvar 'init? #f)))
  (define (binding-initialized? x)   (mvector-ref x 0))
  (define (binding-init-var     x)   (mvector-ref x 1))
  (define (binding-initialize!  x)   (mvector-set! x 0 #t))
  (define (binding-defer!       x t) (mvector-set! x 2 (cons t (mvector-ref x 2))))
  (define (binding-force!       x)   (let ((t* (mvector-ref x 2)))
                                       (mvector-set! x 2 '())
                                       (for-each (lambda (t) (t)) t*)))
  (define (Expr/no-escape x) (Expr/binding #f #f x))
  (define (Expr/binding outer-bnd escape? x)
    (define (loop x) (Expr/binding outer-bnd escape? x))
    (define (Expr x) (Expr/binding outer-bnd #t x))
    (define note (HLL-note x))
    (HLL-case
      x
      ((ref v)
       (let ((bnd (hllvar-data v)))
         (if bnd
             (let ((x (if (binding-initialized? bnd)
                          x
                          (HLL: (if ,(let ((init (binding-init-var bnd)))
                                       (inc-hllvar-refcount! init)
                                       (HLL: (unbox init)))
                                    ,x
                                    (/note note (panic #f "referenced uninitialized variable"
                                                       ',(hllvar-name v))))))))
               (if escape?
                   (binding-force! bnd)
                   (when outer-bnd (binding-defer! outer-bnd (lambda () (binding-force! bnd)))))
               x)
             x)))
      ((primop _)         x)
      ((quote _)          x)
      ((if c t f)         (HLL:if note (Expr/no-escape c) (loop t) (loop f)))
      ((begin e^ e)       (HLL:begin note (tree-map Expr/no-escape e^) (loop e)))
      ((call rator rand*) (HLL:call note (Expr rator) (map Expr rand*)))
      ((case-lambda clc*)
       (define (^expr)
         (HLL:case-lambda note (clc*-map (lambda (a p body) (cl-clause a p (Expr body))) clc*)))
       (cond (escape?   (^expr))
             (outer-bnd (let ((&expr (box #f)))
                          (binding-defer! outer-bnd (lambda () (set-box! &expr (^expr))))
                          (HLL:late #f &expr)))
             (else      (HLL:quote note #t))))
      ((letrec lb* body)
       (lb*-for-each (lambda (lhs _) (when lhs (bind-rec! lhs))) lb*)
       (mdefine init* '())
       (let* ((x (HLL:letrec
                   note
                   (lb*-map
                     (lambda (lhs rhs)
                       (let-binding
                         lhs
                         (if lhs
                             (let* ((bnd (hllvar-data lhs))
                                    (init (binding-init-var bnd))
                                    (rhs (Expr/binding bnd #f rhs)))
                               (binding-initialize! bnd)
                               (if (hllvar-referenced? init)
                                   (let ((rhsvar (hllvar #f #f)))
                                     (inc-hllvar-refcount! init)
                                     (inc-hllvar-refcount! rhsvar)
                                     (set! init* (cons init init*))
                                     (HLL: (let* ((rhsvar ,rhs)) (set-box! init #t) rhsvar)))
                                   rhs))
                             (Expr/no-escape rhs))))
                     lb*)
                   (loop body)))
              (init* init*))
         (if (null? init*)
             x
             (HLL: (let* ,(map (lambda (init) (let-binding init (HLL: (box #f)))) init*) ,x)))))
      ((let* lb* body)
       (lb*-for-each (lambda (lhs _) (when lhs (bind-nonrec! lhs))) lb*)
       (HLL:let* note (lb*-map (lambda (lhs rhs)
                                 (let-binding lhs (Expr/binding (and lhs (hllvar-data lhs)) #f rhs)))
                               lb*)
                 (loop body)))
      ((apply/values rator rand) (HLL:apply/values note (Expr rator) (Expr rand)))
      ((case-values rand clc*)   (define (CLC a p body) (cl-clause a p (loop body)))
                                 (HLL:case-values note (Expr rand) (clc*-map CLC clc*)))
      ((late &e)                 (loop (unbox &e)))))
  (let ((topvar (hllvar #f #f)))
    (bind-nonrec! topvar)
    (let ((P (Expr/binding (hllvar-data topvar) #f P)))
      (let loop () (let ((bnd* bnd*.pending))
                     (set! bnd*.pending '())
                     (unless (null? bnd*) (for-each binding-force! bnd*) (loop))))
      (for-each (lambda (x) (set-hllvar-data! x #f)) var*.all)
      P)))

;; HLL-stratify-letrec is an optional pass that is intended to be run before HLL-convert-letrec so
;; that fewer bindings are converted to boxes.  This pass may also speed up HLL-sink-join-points.
;; If HLL-check-letrec is run, it should be run before HLL-stratify-letrec because the latter may
;; reorder bindings in a way that masks issues with the original initialization order.
;; See these related publications:
;; https://web.archive.org/web/20241217023225/https://legacy.cs.indiana.edu/~dyb/pubs/fixing-letrec.pdf
;; https://web.archive.org/web/20240113151850/https://legacy.cs.indiana.edu/~dyb/pubs/letrec-reloaded.pdf
(define (HLL-stratify-letrec P)
  (define (make-node lhs rhs cl? &active-src) (mvector lhs rhs cl? '() &active-src #f))
  (define (node-lhs         n) (mvector-ref n 0))
  (define (node-rhs         n) (mvector-ref n 1))
  (define (node-cl?         n) (mvector-ref n 2))
  (define (node-edge*       n) (mvector-ref n 3))
  (define (node-&active-src n) (mvector-ref n 4))  ; phase 1 (graph construction)
  (define (node-recent-src  n) (mvector-ref n 5))  ; phase 1
  (define (set-node-rhs!         n r) (mvector-set! n 1 r))
  (define (set-node-recent-src!  n x) (mvector-set! n 5 x))  ; phase 1
  (define (node-link!            n m) (mvector-set! n 3 (cons m (node-edge* n))))
  (define (node-active-src-link! n)   (let ((src (unbox (node-&active-src n))))
                                        (unless (eqv? (node-recent-src n) src)
                                          (set-node-recent-src! n src)
                                          (node-link! src n))))
  (define (node-visit-index n) (mvector-ref n 4))  ; phase 2 (SCC topological sort)
  (define (node-scc-index   n) (mvector-ref n 5))  ; phase 2
  (define (set-node-visit-index! n vi) (mvector-set! n 4 vi))  ; phase 2
  (define (set-node-scc-index!   n si) (mvector-set! n 5 si))  ; phase 2
  (define (CLC* clc*) (clc*-map (lambda (a p body) (cl-clause a p (Expr body))) clc*))
  (define (Expr x)
    (define note (HLL-note x))
    (HLL-case
      x
      ((ref v)            (let ((n (hllvar-data v))) (when n (node-active-src-link! n)))
                          x)
      ((primop _)         x)
      ((quote v)          x)
      ((if c t f)         (HLL:if note (Expr c) (Expr t) (Expr f)))
      ((begin e^ e)       (HLL:begin note (tree-map Expr e^) (Expr e)))
      ((call rator rand*) (HLL:call note (Expr rator) (map Expr rand*)))
      ((case-lambda clc*) (HLL:case-lambda note (CLC* clc*)))
      ((letrec lb* body)
       (define &active-src (box #f))
       (define (node-Expr-rhs! n) (set-box! &active-src n) (set-node-rhs! n (Expr (node-rhs n))))
       (define (stratify node node*)
         (for-each (lambda (n)
                     (let ((lhs (node-lhs n))) (when lhs (set-hllvar-data! lhs #f)))
                     (set-node-visit-index! n #f)
                     (set-node-scc-index! n #f))
                   (cons node node*))
         (let loop ((node node) (node* node*))
           (if (HLL-pure? (node-rhs node))
               (unless (null? node*) (loop (car node*) (cdr node*)))
               (let loop ((impure node) (node* node*))
                 (unless (null? node*)
                   (let ((node (car node*)) (node* (cdr node*)))
                     (if (HLL-pure? (node-rhs node))
                         (loop impure node*)
                         (begin (node-link! node impure) (loop node node*))))))))
         (mlet ((vi 0) (si 0))
           (define (make-scc root-index node^) (cons root-index node^))
           (define (scc-root-index scc) (car scc))
           (define (scc-node^      scc) (cdr scc))
           (define (scc-unite a b) (make-scc (min (scc-root-index a) (scc-root-index b))
                                             (cons (scc-node^ a) (scc-node^ b))))
           (define (scc-raise scc root-index) (if (< root-index (scc-root-index scc))
                                                  (make-scc root-index (scc-node^ scc))
                                                  scc))
           (define (finish-scc! scc)
             (let ((si.current si))
               (set! si (+ si.current 1))
               (let loop ((n^ (scc-node^ scc)))
                 (if (pair? n^)
                     (begin (loop (car n^)) (loop (cdr n^)))
                     (set-node-scc-index! n^ si.current)))))
           (define (node-finished? n) (node-scc-index n))
           (define (node-visited? n) (node-visit-index n))
           (define (node-visit! n)
             (unless (node-visited? n)
               (let visit ((n n))
                 (let ((vi.current vi))
                   (set-node-visit-index! n vi.current)
                   (set! vi (+ vi.current 1))
                   (let loop ((n* (node-edge* n)) (scc (make-scc vi.current n)))
                     (cond ((not (null? n*))
                            (let ((n (car n*)))
                              (loop (cdr n*) (cond ((not (node-visited? n))
                                                    (let ((scc? (visit n)))
                                                      (if scc? (scc-unite scc scc?) scc)))
                                                   ((node-finished? n) scc)
                                                   (else (scc-raise scc (node-visit-index n)))))))
                           ((< (scc-root-index scc) vi.current) scc)
                           (else (finish-scc! scc) #f)))))))
           (node-visit! node)
           (for-each node-visit! node*)
           (let* ((slen si) (scc* (make-mvector slen '())))
             (let loop ((node node) (node* node*))
               (let ((si (node-scc-index node)))
                 (mvector-set! scc* si (cons node (mvector-ref scc* si))))
               (unless (null? node*) (loop (car node*) (cdr node*))))
             (let loop ((si 0) (rlb* '()))
               (define (wrap-rlb* body) (if (null? rlb*) body (HLL:let* #f (reverse rlb*) body)))
               (if (< si slen)
                   (let ((n* (mvector-ref scc* si)) (si (+ si 1)))
                     (if (null? (cdr n*))
                         (let* ((n (car n*)) (lb (let-binding (node-lhs n) (node-rhs n))))
                           (if (memv n (node-edge* n))
                               (wrap-rlb* (HLL:letrec #f (list lb) (loop si '())))
                               (loop si (cons lb rlb*))))
                         (let ((lb* (let loop ((n* n*) (lb* '()) (cllb* '()))
                                      (if (null? n*)
                                          (append cllb* lb*)
                                          (let ((n (car n*)) (n* (cdr n*)))
                                            (let ((lb (let-binding (node-lhs n) (node-rhs n))))
                                              (if (node-cl? n)
                                                  (loop n* lb* (cons lb cllb*))
                                                  (loop n* (cons lb lb*) cllb*))))))))
                           (wrap-rlb* (HLL:letrec #f lb* (loop si '()))))))
                   (wrap-rlb* (Expr body)))))))
       (let ((node* (let loop ((lb* lb*) (node*.tail '()))
                      (if (null? lb*)
                          node*.tail
                          (let ((lb (car lb*)) (node* (loop (cdr lb*) node*.tail)))
                            (let handle-lb ((lhs (let-binding-lhs lb)) (rhs (let-binding-rhs lb)))
                              (let retry ((rhs rhs))
                                (define (finish cl?)
                                  (let ((node (make-node lhs rhs cl? &active-src)))
                                    (when lhs (set-hllvar-data! lhs node))
                                    (cons node node*)))
                                (HLL-case
                                  rhs
                                  ((letrec lb* body) (loop lb* (handle-lb lhs body)))
                                  ((let*   lb* body) (loop lb* (handle-lb lhs body)))
                                  ((late   &e)       (retry (unbox &e)))
                                  ((case-lambda _)   (finish #t))
                                  (_                 (finish #f))))))))))
         (let loop ((node* node*) (rlb* '()))
           (define (wrap-rlb* body) (if (null? rlb*) body (HLL:let* #f (reverse rlb*) body)))
           (if (null? node*)
               (wrap-rlb* (Expr body))
               (let ((node (car node*)) (node* (cdr node*)))
                 (node-Expr-rhs! node)
                 (let ((edge* (node-edge* node)))
                   (cond ((null? edge*)  ; no recursion
                          (let ((lhs (node-lhs node)))
                            (when lhs (set-hllvar-data! lhs #f))
                            (loop node* (cons (let-binding lhs (node-rhs node)) rlb*))))
                         ((and (eqv? (car edge*) node) (null? (cdr edge*)))  ; self-reference only
                          (let ((lhs (node-lhs node)))
                            (set-hllvar-data! lhs #f)
                            (wrap-rlb* (HLL:letrec #f (list (let-binding lhs (node-rhs node)))
                                                   (loop node* '())))))
                         (else (for-each node-Expr-rhs! node*)  ; at least one downward edge
                               (wrap-rlb* (stratify node node*))))))))))
      ((let* lb* body)           (let ((lb* (lb*-map (lambda (l r) (let-binding l (Expr r))) lb*)))
                                   (HLL:let* note lb* (Expr body))))
      ((apply/values rator rand) (HLL:apply/values note (Expr rator) (Expr rand)))
      ((case-values rand clc*)   (HLL:case-values note (Expr rand) (CLC* clc*)))
      ((late &e)                 (Expr (unbox &e)))))
  (Expr P))

;; HLL-sink-join-points is a direct-style approach to contification.
;; See the following for detail about contification in CPS and SSA:
;; https://www.cs.rit.edu/~mtf/research/contification/ICFP01/icfp01.pdf
;; https://www.microsoft.com/en-us/research/wp-content/uploads/2007/10/compilingwithcontinuationscontinued.pdf
;; For efficiency, it is recommended to HLL-stratify-letrec before HLL-sink-join-points.
;; - For pathological inputs, this solution is quadratic in the size of a letrec binding graph
;;   because it implicitly builds a dominator tree by iterating knode-parent updates and meets.
;; - But this could be improved by reframing the solution in terms of an explicit dominator tree
;;   that is built more efficiently.
(define (HLL-sink-join-points P)
  (mdefine join-point* '())
  (define k.escape #f)
  (define k.pending 'pending)
  (define k-escape? not)
  (define (k-pending? k) (eqv? k k.pending))
  (define (make-knode rec? parent)
    (let ((kn (mvector #f (if (k-escape? parent) 0 (+ (knode-level parent) 1))
                       parent #f '() (if rec? '() #f))))
      (mvector-set! kn 0 (if (k-escape? parent) kn (knode-root0 parent)))
      kn))
  (define (make-knode-rec    parent) (make-knode #t parent))
  (define (make-knode-nonrec parent) (make-knode #f parent))
  (define (knode-root0   kn) (mvector-ref kn 0))
  (define (knode-level   kn) (mvector-ref kn 1))
  (define (knode-parent  kn) (mvector-ref kn 2))
  (define (knode-body    kn) (mvector-ref kn 3))
  (define (knode-sink*   kn) (mvector-ref kn 4))
  (define (knode-passed* kn) (mvector-ref kn 5))
  (define (set-knode-parent!  kn x)  (mvector-set! kn 2 x))
  (define (set-knode-body!    kn b)  (mvector-set! kn 3 b))
  (define (set-knode-sink*!   kn x*) (mvector-set! kn 4 x*))
  (define (set-knode-passed*! kn x*) (mvector-set! kn 5 x*))
  (define (knode-sink! kn lb) (set-knode-sink*! kn (cons lb (knode-sink* kn))))
  (define (knode-pass! kn x) (let ((passed* (knode-passed* kn)))
                               (when passed* (set-knode-passed*! kn (cons x passed*)))))
  (define (knode-call-passed! kn)
    (for-each (let ((k (knode-parent kn))) (lambda (c) (candidate-call! c k))) (knode-passed* kn)))
  (define (knode-bind! kn lb* rec?)
    (let ((b (knode-body kn))) (set-box! b ((if rec? HLL:letrec HLL:let*) #f lb* (unbox b)))))
  (define (make-candidate k.home rhs queue) (mvector k.home k.pending queue rhs #f))
  (define (candidate-home-k    c) (mvector-ref c 0))
  (define (candidate-current-k c) (mvector-ref c 1))
  (define (candidate-queue     c) (mvector-ref c 2))
  (define (candidate-rhs       c) (mvector-ref c 3))
  (define (candidate-body-k*   c) (mvector-ref c 4))
  (define (set-candidate-current-k! c x) (mvector-set! c 1 x))
  (define (set-candidate-queue!     c x) (mvector-set! c 2 x))
  (define (set-candidate-rhs!       c x) (mvector-set! c 3 x))
  (define (set-candidate-body-k*!   c x) (mvector-set! c 4 x))
  (define (candidate-call! c k)
    (define (update! knext)
      (set-candidate-current-k! c knext)
      (unless (or (k-escape? knext) (knode-body knext)) (set-knode-body! knext (box #f)))
      (let ((body-k* (candidate-body-k* c)))
        (when body-k* (for-each (lambda (k) (set-knode-parent! k knext)) body-k*)))
      (let ((q (candidate-queue c))) (when q (queue-push! q c))))
    (let ((k.c (candidate-current-k c)))
      (unless (or (k-escape? k.c) (eqv? k k.c))
        (cond
          ((or (k-pending? k.c) (k-escape? k))            (update! k))
          ((not (eqv? (knode-root0 k) (knode-root0 k.c))) (update! k.escape))
          (else (let meet ((a k) (la (knode-level k)) (b k.c) (lb (knode-level k.c)))
                  (cond ((< la lb)
                         (let ((b0 b) (b (knode-parent b)))
                           (cond ((k-escape? b) (update! k.escape))
                                 (else (knode-pass! b0 c)
                                       (if (eqv? a b)
                                           (unless (eqv? k.c a) (update! a))
                                           (meet a la b (knode-level b)))))))
                        ((< lb la)
                         (let ((a0 a) (a (knode-parent a)))
                           (cond ((k-escape? a) (update! k.escape))
                                 (else (knode-pass! a0 c)
                                       (if (eqv? a b)
                                           (unless (eqv? k.c a) (update! a))
                                           (meet a (knode-level a) b lb))))))
                        (else
                          (let ((a0 a) (b0 b) (a (knode-parent a)) (b (knode-parent b)))
                            (cond ((k-escape? a) (update! k.escape))
                                  ((k-escape? b) (update! k.escape))
                                  (else (knode-pass! a0 c) (knode-pass! b0 c)
                                        (if (eqv? a b)
                                            (unless (eqv? k.c a) (update! a))
                                            (meet a (knode-level a) b (knode-level b))))))))))))))
  (define (make-queue) (box '()))
  (define (queue-empty? q) (null? (unbox q)))
  (define (queue-push! q c) (set-candidate-queue! c #f) (set-box! q (cons c (unbox q))))
  (define (queue-run! q) (let ((c* (unbox q)))
                           (set-box! q '())
                           (for-each (lambda (c)
                                       (set-candidate-queue! c q)
                                       (let ((body-k* (candidate-body-k* c)))
                                         (if body-k*
                                             (for-each knode-call-passed! body-k*)
                                             (set-candidate-rhs! c (JP-rec c)))))
                                     c*)))
  (define (lb*-register lb* k.home queue)
    (let loop ((lb* lb*))
      (if (null? lb*)
          '()
          (let ((lb (car lb*)) (lb* (loop (cdr lb*))))
            (let ((lhs (let-binding-lhs lb)))
              (let ((rhs (and lhs (let retry ((rhs (let-binding-rhs lb)))
                                    (HLL-case rhs
                                              ((case-lambda _) rhs)
                                              ((late &e)       (retry (unbox &e)))
                                              (_               #f))))))
                (if rhs
                    (begin (set-hllvar-data! lhs (make-candidate k.home rhs queue)) (cons lhs lb*))
                    lb*)))))))
  (define (CLC*/Expr Expr clc*) (clc*-map (lambda (a p b) (cl-clause a p (Expr b))) clc*))
  (define (Late/k k x) (let ((e (Expr/k k x)) (b (knode-body k)))
                         (if b (begin (set-box! b e) (HLL:late #f b)) e)))
  (define (Nontail x) (Late/k (make-knode-nonrec k.escape) x))
  (define (Ref k v x) (let ((c (hllvar-data v))) (when c (candidate-call! c k))) x)
  (define (JP-rec c)
    (let ((k (candidate-current-k c)) (x (candidate-rhs c)))
      (HLL-case
        x
        ((case-lambda clc*)
         (mdefine body-k* '())
         (let ((x (HLL:case-lambda (HLL-note x) (CLC*/Expr (lambda (x)
                                                             (let ((k (make-knode-rec k)))
                                                               (set! body-k* (cons k body-k*))
                                                               (Late/k k x)))
                                                           clc*))))
           (set-candidate-body-k*! c body-k*)
           x)))))
  (define (JP-nonrec k c)
    (let ((x (candidate-rhs c)))
      (HLL-case x ((case-lambda clc*)
                   (HLL:case-lambda (HLL-note x) (CLC*/Expr (lambda (x) (Expr/k k x)) clc*))))))
  (define (Expr/k k x)
    (define (Tail x) (Expr/k k x))
    (define (Rator x) (HLL-case x ((ref v) (Ref k v x)) (_ (Nontail x))))
    (define note (HLL-note x))
    (HLL-case
      x
      ((ref v)            (Ref k.escape v x))
      ((primop _)         x)
      ((quote _)          x)
      ((if c t f)         (HLL:if note (Nontail c) (Tail t) (Tail f)))
      ((begin e^ e)       (HLL:begin note (tree-map Nontail e^) (Tail e)))
      ((call rator rand*) (HLL:call note (Rator rator) (map Nontail rand*)))
      ((case-lambda clc*) (HLL:case-lambda note (CLC*/Expr Nontail clc*)))
      ((letrec lb* body)
       (mdefine k*.sink '())
       (let* ((q (make-queue))
              (registered* (lb*-register lb* k q))
              (body (Tail body))
              (lb* (let loop ((lb* lb*))
                     (if (null? lb*)
                         '()
                         (let ((lb (car lb*)) (lb* (loop (cdr lb*))))
                           (let ((lhs (let-binding-lhs lb)))
                             (if (and lhs (hllvar-data lhs))
                                 lb*
                                 (cons (let-binding lhs (Nontail (let-binding-rhs lb))) lb*)))))))
              (lb* (begin
                     (let loop () (unless (queue-empty? q) (queue-run! q) (loop)))
                     (let loop ((lhs* registered*))
                       (if (null? lhs*)
                           lb*
                           (let ((lhs (car lhs*)) (lb* (loop (cdr lhs*))))
                             (let* ((c (hllvar-data lhs)) (k.c (candidate-current-k c)))
                               (cond ((k-pending? k.c) lb*)
                                     ((k-escape? k.c)
                                      (cons (let-binding lhs (candidate-rhs c)) lb*))
                                     ((eqv? (candidate-home-k c) k.c)
                                      (set! join-point* (cons lhs join-point*))
                                      (cons (let-binding lhs (candidate-rhs c)) lb*))
                                     (else (knode-sink! k.c (let-binding lhs (candidate-rhs c)))
                                           (set! k*.sink (cons k.c k*.sink))
                                           (set! join-point* (cons lhs join-point*))
                                           lb*)))))))))
         (for-each (lambda (kn) (let ((lb* (knode-sink* kn))) (unless (null? lb*)
                                                                (set-knode-sink*! kn '())
                                                                (knode-bind! kn lb* #t))))
                   k*.sink)
         (for-each (lambda (x) (set-hllvar-data! x #f)) registered*)
         (if (null? lb*) body (HLL:letrec note lb* body))))
      ((let* lb* body)
       (mdefine k*.sink '())
       (let ((registered* (lb*-register lb* k #f))
             (body (Tail body))
             (lb* (let loop ((lb* lb*))
                    (if (null? lb*)
                        '()
                        (let* ((lb (car lb*))
                               (lb* (loop (cdr lb*)))
                               (lhs (let-binding-lhs lb)) (rhs (let-binding-rhs lb))
                               (c (and lhs (hllvar-data lhs)))
                               (k.c (if c (candidate-current-k c) k.escape)))
                          (cond ((k-pending? k.c) lb*)
                                ((k-escape? k.c) (cons (let-binding lhs (Nontail rhs)) lb*))
                                ((eqv? (candidate-home-k c) k.c)
                                 (set! join-point* (cons lhs join-point*))
                                 (cons (let-binding lhs (JP-nonrec k.c c)) lb*))
                                (else (knode-sink! k.c (let-binding lhs (JP-nonrec k.c c)))
                                      (set! k*.sink (cons k.c k*.sink))
                                      (set! join-point* (cons lhs join-point*))
                                      lb*)))))))
         (for-each (lambda (kn) (let ((lb* (knode-sink* kn))) (unless (null? lb*)
                                                                (set-knode-sink*! kn '())
                                                                (knode-bind! kn lb* #f))))
                   k*.sink)
         (for-each (lambda (x) (set-hllvar-data! x #f)) registered*)
         (if (null? lb*) body (HLL:let* note lb* body))))
      ((apply/values rator rand) (HLL:apply/values note (Nontail rator) (Nontail rand)))
      ((case-values rand clc*)   (HLL:case-values note (Nontail rand) (CLC*/Expr Tail clc*)))
      ((late &e)                 (Tail (unbox &e)))))
  (let ((P (Nontail P))) (values join-point* P)))

(define (HLL-convert-letrec P)
  (let Expr ((x P))
    (define (CLC* clc*) (clc*-map (lambda (a p body) (cl-clause a p (Expr body))) clc*))
    (define note (HLL-note x))
    (HLL-case
      x
      ((ref v)            (if (hllvar-data v) (HLL: (/note note (unbox v))) x))
      ((primop _)         x)
      ((quote v)          x)
      ((if c t f)         (HLL:if note (Expr c) (Expr t) (Expr f)))
      ((begin e^ e)       (HLL:begin note (tree-map Expr e^) (Expr e)))
      ((call rator rand*) (HLL:call note (Expr rator) (map Expr rand*)))
      ((case-lambda clc*) (HLL:case-lambda note (CLC* clc*)))
      ((letrec lb* body)
       (mdefine lb*.lam '())
       (mdefine lb*.other '())
       (lb*-for-each (lambda (lhs rhs)
                       (let retry ((rhs rhs))
                         (HLL-case
                           rhs
                           ((case-lambda clc*) (set! lb*.lam (cons (let-binding lhs rhs) lb*.lam)))
                           ((late &e) (retry (unbox &e)))
                           (_ (when lhs (set-hllvar-data! lhs #t))
                              (set! lb*.other (cons (let-binding lhs rhs) lb*.other))))))
                     lb*)
       (mdefine lb*.box '())
       (mdefine effect^ #f)
       (define (effect! e) (let ((e^ effect^)) (if e^ (set! effect^ (cons e e^)) (set! effect^ e))))
       (lb*-for-each (lambda (lhs rhs)
                       (let ((rhs (Expr rhs)))
                         (if lhs
                             (begin (set! lb*.box (cons (let-binding lhs (HLL: (box #t))) lb*.box))
                                    (effect! (HLL: (set-box! lhs ,rhs))))
                             (effect! rhs))))
                     lb*.other)
       (let* ((body (let ((e^ effect^) (body (Expr body))) (if e^ (HLL: (begin ,e^ ,body)) body)))
              (lb*.lam (lb*-map (lambda (lhs rhs) (let-binding lhs (Expr rhs))) (reverse lb*.lam)))
              (body (if (null? lb*.lam) body (HLL:letrec note lb*.lam body)))
              (lb*.box lb*.box)
              (body (if (null? lb*.box) body (HLL:let* #f lb*.box body))))
         (lb*-for-each (lambda (lhs _) (set-hllvar-data! lhs #f)) lb*.box)
         body))
      ((let* lb* body)           (define (LB lhs rhs) (let-binding lhs (Expr rhs)))
                                 (HLL:let* note (lb*-map LB lb*) (Expr body)))
      ((apply/values rator rand) (HLL:apply/values note (Expr rator) (Expr rand)))
      ((case-values rand clc*)   (HLL:case-values note (Expr rand) (CLC* clc*)))
      ((late &e)                 (Expr (unbox &e))))))

(define (HLL-bind-lambda P)
  (define (CLC* clc*) (clc*-map (lambda (a p body) (cl-clause a p (Expr body))) clc*))
  (define (Expr x) (Expr/k x values (lambda (rhs) (let ((lhs (hllvar #f #f)))
                                                    (HLL: (letrec ((lhs ,rhs)) lhs))))))
  (define (Expr/k x k k.lambda)
    (define (Expr/current x) (Expr/k x k k.lambda))
    (define note (HLL-note x))
    (HLL-case
      x
      ((ref _)            (k x))
      ((primop _)         (k x))
      ((quote _)          (k x))
      ((if c t f)         (k (HLL:if note (Expr c) (Expr t) (Expr f))))
      ((begin e^ e)       (k (HLL:begin note (tree-map Expr e^) (Expr e))))
      ((call rator rand*) (k (HLL:call note (Expr rator) (map Expr rand*))))
      ((case-lambda clc*) (k.lambda (HLL:case-lambda note (CLC* clc*))))
      ((letrec lb* body)  (define (LB lhs rhs) (let-binding lhs (Expr/k rhs values values)))
                          (k (HLL:letrec note (lb*-map LB lb*) (Expr body))))
      ((let* lb* body)
       (if (null? lb*)
           (Expr/current body)
           (k (let outer-loop ((note note) (lb* lb*))
                (if (null? lb*)
                    (Expr body)
                    (let ((lb (car lb*)) (lb* (cdr lb*)))
                      (let ((lhs (let-binding-lhs lb)) (rhs (let-binding-rhs lb)))
                        (define (k rhs)
                          (let split-loop ((lb* lb*) (prev* (list (let-binding lhs rhs))))
                            (if (null? lb*)
                                (HLL: (/note note (let* ,(reverse prev*) ,(Expr body))))
                                (let ((lb (car lb*)) (lb* (cdr lb*)))
                                  (let ((lhs (let-binding-lhs lb)) (rhs (let-binding-rhs lb)))
                                    (define (k rhs)
                                      (split-loop lb* (cons (let-binding lhs rhs) prev*)))
                                    (define (k.lambda rhs)
                                      (HLL: (/note note (let* ,(reverse prev*)
                                                          (letrec ((lhs ,rhs))
                                                            ,(outer-loop #f lb*))))))
                                    (Expr/k rhs k k.lambda))))))
                        (define (k.lambda rhs) (HLL: (/note note (letrec ((lhs ,rhs))
                                                                   ,(outer-loop #f lb*)))))
                        (Expr/k rhs k k.lambda))))))))
      ((apply/values rator rand) (k (HLL:apply/values note (Expr rator) (Expr rand))))
      ((case-values rand clc*)   (k (HLL:case-values note (Expr rand) (CLC* clc*))))
      ((late &e)                 (Expr/current (unbox &e)))))
  (Expr P))

(define (HLL-map-quote P f)
  (define (Let-binding* lb*) (lb*-map (lambda (lhs rhs) (let-binding lhs (Expr rhs))) lb*))
  (define (CLC* clc*)
    (clc*-map (lambda (arity param body) (cl-clause arity param (Expr body))) clc*))
  (define (Expr x)
    (define note (HLL-note x))
    (HLL-case
      x
      ((ref _)                   x)
      ((primop _)                x)
      ((quote v)                 (f x note v))
      ((if c t f)                (HLL:if note (Expr c) (Expr t) (Expr f)))
      ((begin e^ e)              (HLL:begin note (tree-map Expr e^) (Expr e)))
      ((call rator rand*)        (HLL:call note (Expr rator) (map Expr rand*)))
      ((case-lambda clc*)        (HLL:case-lambda note (CLC* clc*)))
      ((letrec lb* body)         (HLL:letrec note (Let-binding* lb*) (Expr body)))
      ((let* lb* body)           (HLL:let*   note (Let-binding* lb*) (Expr body)))
      ((apply/values rator rand) (HLL:apply/values note (Expr rator) (Expr rand)))
      ((case-values rand clc*)   (HLL:case-values note (Expr rand) (CLC* clc*)))
      ((late &e)                 (Expr (unbox &e)))))
  (Expr P))

(define (HLL-normalize-quote P)
  (mdefine lb* '())
  (define (proc->primop proc note) (let ((p (procedure->primop proc)))
                                     (if p (HLL:primop note p) (HLL:quote note proc))))
  (define p.cons   (proc->primop cons #f))
  (define p.vector (proc->primop vector #f))
  (let ((x (HLL-map-quote
             P (lambda (x note v)
                 (let loop/note ((v v) (note note))
                   (define (loop v) (loop/note v #f))
                   (cond ((immediate? v) (HLL:quote note v))
                         ((procedure? v) (proc->primop v note))
                         (else (let ((t (hllvar #f #f))
                                     (x (cond ((pair? v) (HLL:call p.cons #f (list (loop (car v))
                                                                                   (loop (cdr v)))))
                                              ((vector? v) (HLL:call p.vector #f
                                                                     (map loop (vector->list v))))
                                              (else (HLL:quote #f v)))))
                                 (set! lb* (cons (let-binding t x) lb*))
                                 (HLL:ref note t)))))))))
    (if (null? lb*) x (HLL:let* #f lb* x))))

(define (HLL-procedure=>free-variable* P)
  (define (make-clo) (box '()))
  (define (clo-free! clo v) (set-box! clo (cons v (unbox clo))))
  (define (make-seen clo* depth) (mvector depth clo* depth))
  (define (seen-top-depth s) (mvector-ref s 0))
  (define (seen-clo*      s) (mvector-ref s 1))
  (define (seen-depth     s) (mvector-ref s 2))
  (define (seen-set! s clo* depth) (mvector-set! s 1 clo*) (mvector-set! s 2 depth))
  (mdefine lhs=>clo '())
  (let loop/lhs ((lhs #f) (clo* '()) (depth 0) (x P))
    (define (loop/clo* clo* depth x) (loop/lhs #f clo* depth x))
    (define (loop x) (loop/clo* clo* depth x))
    (define (Let lb* body)
      (lb*-for-each (lambda (lhs _) (when lhs (set-hllvar-data! lhs (make-seen clo* depth)))) lb*)
      (lb*-for-each (lambda (lhs rhs) (loop/lhs lhs clo* depth rhs)) lb*)
      (loop body)
      (lb*-for-each (lambda (lhs _) (when lhs (set-hllvar-data! lhs #f))) lb*))
    (define (CLC* clc* clo* depth)
      (clc*-for-each (lambda (a p*~ body)
                       (param-for-each (lambda (p) (set-hllvar-data! p (make-seen clo* depth))) p*~)
                       (loop/clo* clo* depth body)
                       (param-for-each (lambda (p) (set-hllvar-data! p #f)) p*~))
                     clc*))
    (HLL-case
      x
      ((ref v)
       (let* ((s (hllvar-data v)) (td (seen-top-depth s)) (d (seen-depth s)) (c* (seen-clo* s)))
         (unless (= td 0)  ; NOTE: top-level variables are not stored in closures
           (seen-set! s clo* depth)
           (define (k d c* clo*) (when (< td d) (let ((clo (car clo*)))
                                                  (unless (eqv? clo (car c*))
                                                    (clo-free! clo v)
                                                    (k (- d 1) (cdr c*) (cdr clo*))))))
           (if (< d depth)
               (let loop ((depth depth) (clo* clo*))
                 (clo-free! (car clo*) v)
                 (let ((depth (- depth 1)) (clo* (cdr clo*)))
                   (if (< d depth) (loop depth clo*) (k d c* clo*))))
               (k depth (drop (- d depth) c*) clo*)))))
      ((primop _)                (values))
      ((quote _)                 (values))
      ((if c t f)                (loop c) (loop t) (loop f))
      ((begin e^ e)              (tree-for-each loop e^) (loop e))
      ((call rator rand*)        (loop rator) (for-each loop rand*))
      ((case-lambda clc*)        (let* ((clo (make-clo)) (clo* (cons clo clo*)) (depth (+ depth 1)))
                                   (set! lhs=>clo (cons (cons lhs clo) lhs=>clo))
                                   (CLC* clc* clo* depth)))
      ((letrec lb* body)         (Let lb* body))
      ((let* lb* body)           (Let lb* body))
      ((apply/values rator rand) (loop rator) (loop rand))
      ((case-values rand clc*)   (loop rand) (CLC* clc* clo* depth))
      ((late &e)                 (loop (unbox &e)))))
  (alist-map-value unbox lhs=>clo))

(define (HLL-well-known-procedure* P var*.procedure)
  (for-each (lambda (v) (set-hllvar-data! v #t)) var*.procedure)
  (define (Let lb* body) (lb*-for-each (lambda (_ rhs) (Expr rhs)) lb*) (Expr body))
  (define (CLC* clc*) (clc*-for-each (lambda (a p body) (Expr body)) clc*))
  (define (Expr x) (Expr/rator? #f x))
  (define (Expr/rator? rator? x)
    (HLL-case
      x
      ((ref v)                   (unless rator? (set-hllvar-data! v #f)))
      ((primop _)                (values))
      ((quote _)                 (values))
      ((if c t f)                (Expr c) (Expr t) (Expr f))
      ((begin e^ e)              (tree-for-each Expr e^) (Expr e))
      ((call rator rand*)        (Expr/rator? #t rator) (for-each Expr rand*))
      ((case-lambda clc*)        (CLC* clc*))
      ((letrec lb* body)         (Let lb* body))
      ((let* lb* body)           (Let lb* body))
      ((apply/values rator rand) (Expr rator) (Expr rand))
      ((case-values rand clc*)   (Expr rand) (CLC* clc*))
      ((late &e)                 (Expr/rator? rator? (unbox &e)))))
  (Expr P)
  (filter (lambda (v) (let ((wk? (hllvar-data v))) (set-hllvar-data! v #f) wk?)) var*.procedure))

;; Recognize joint points as described in:
;; https://www.microsoft.com/en-us/research/wp-content/uploads/2016/11/compiling-without-continuations.pdf
;; NOTE: rather than transform join points, we will transform exit points directly, inspired by:
;; https://www.cs.purdue.edu/homes/rompf/papers/cong-icfp19.pdf
(define (HLL-join-point* P var*.well-known)
  (define (make-candidate) (make-mvector 2 #f))
  (define (candidate-level c) (mvector-ref c 0))
  (define (candidate-rhs   c) (mvector-ref c 1))
  (define (candidate-set! c level rhs)
    (mvector-set! c 0 level)
    (mvector-set! c 1 rhs))
  (for-each (lambda (v) (set-hllvar-data! v (make-candidate))) var*.well-known)
  (mdefine non-tail* '())
  (define (Expr/level level x)
    (define level+1 (and level (+ level 1)))
    (define (Expr x) (Expr/level level+1 x))
    (define (Tail x) (Expr/level level x))
    (define (CLC* clc*) (clc*-for-each (lambda (a p body) (Tail body)) clc*))
    (HLL-case
      x
      ((ref v)                   (let ((c (hllvar-data v)))
                                   (when (and c (not (eqv? (candidate-level c) level)))
                                     (set-hllvar-data! v #f)
                                     (set! non-tail* (cons c non-tail*)))))
      ((primop _)                (values))
      ((quote _)                 (values))
      ((if c t f)                (Expr c) (Tail t) (Tail f))
      ((begin e^ e)              (tree-for-each Expr e^) (Tail e))
      ((call rator rand*)        (Tail rator) (for-each Expr rand*))
      ((case-lambda clc*)        (CLC* clc*))
      ((letrec lb* body)         (lb*-for-each (lambda (lhs rhs)
                                                 (let ((c (and lhs (hllvar-data lhs))))
                                                   (when c (candidate-set! c level rhs))))
                                               lb*)
                                 (Tail body)
                                 (lb*-for-each (lambda (lhs rhs) (if (and lhs (hllvar-data lhs))
                                                                     (Tail rhs)
                                                                     (Expr rhs)))
                                               lb*))
      ((let* lb* body)           (lb*-for-each (lambda (_ rhs) (Expr rhs)) lb*) (Tail body))
      ((apply/values rator rand) (Expr rator) (Expr rand))
      ((case-values rand clc*)   (Expr rand) (CLC* clc*))
      ((late &e)                 (Tail (unbox &e)))))
  (Expr/level 0 P)
  (let loop () (let ((c* non-tail*))
                 (unless (null? c*)
                   (set! non-tail* '())
                   (for-each (lambda (c) (Expr/level (+ (candidate-level c) 1) (candidate-rhs c)))
                             c*)
                   (loop))))
  (filter (lambda (v) (let ((jp? (hllvar-data v))) (set-hllvar-data! v #f) jp?)) var*.well-known))
