(define env.base     (env-conjoin* env.small (eval-definition* env.small def*.base)))
(define env.compiler (eval-definition* env.base def*.compiler))
(define env.nscheme  (let ((env.deps (env-conjoin* env.base env.syntax env.compiler)))
                       (env-conjoin* env.deps env.meta (eval-definition* env.deps def*.nscheme))))
(define env.large    env.nscheme)
