(define (fresh-address name) (vector name))

;; TODO: define IR with record types for capability security
;; TODO: support for lower-level language integration:
;; - E:unchecked-call, E:let with type info, E:case-lambda with type info, etc.
(define (E:annotated   pv E)           (vector 'E:annotated   pv E))
(define (E:prim        name)           (vector 'E:prim        name))
(define (E:quote       v)              (vector 'E:quote       v))
(define (E:ref         address)        (vector 'E:ref         address))
(define (E:if          c t f)          (vector 'E:if          c t f))
(define (E:call        proc args)      (vector 'E:call        proc args))
(define (E:case-lambda param* body*)   (vector 'E:case-lambda param* body*))
(define (E:letrec      lhs* rhs* body) (vector 'E:letrec      lhs* rhs* body))

(define (E-tag                   E)     (vector-ref E 0))
(define (E-tagged?               E tag) (eq? (E-tag E) tag))
(define (E:annotated?            E)     (E-tagged? E 'E:annotated))
(define (E:prim?                 E)     (E-tagged? E 'E:prim))
(define (E:quote?                E)     (E-tagged? E 'E:quote))
(define (E:ref?                  E)     (E-tagged? E 'E:ref))
(define (E:if?                   E)     (E-tagged? E 'E:if))
(define (E:call?                 E)     (E-tagged? E 'E:call))
(define (E:case-lambda?          E)     (E-tagged? E 'E:case-lambda))
(define (E:letrec?               E)     (E-tagged? E 'E:letrec))
(define (E:annotated-provenance  E)     (vector-ref E 1))
(define (E:annotated-E           E)     (vector-ref E 2))
(define (E:prim-name             E)     (vector-ref E 1))
(define (E:quote-value           E)     (vector-ref E 1))
(define (E:ref-address           E)     (vector-ref E 1))
(define (E:if-condition          E)     (vector-ref E 1))
(define (E:if-consequent         E)     (vector-ref E 2))
(define (E:if-alternative        E)     (vector-ref E 3))
(define (E:call-operator         E)     (vector-ref E 1))
(define (E:call-operand*         E)     (vector-ref E 2))
(define (E:case-lambda-param*    E)     (vector-ref E 1))
(define (E:case-lambda-body*     E)     (vector-ref E 2))
(define (E:letrec-binding-left*  E)     (vector-ref E 1))
(define (E:letrec-binding-right* E)     (vector-ref E 2))
(define (E:letrec-body           E)     (vector-ref E 3))

(define (E-provenance     E) (and (E:annotated? E) (E:annotated-provenance E)))
(define (E-provenance-add E pv)
  (if pv
      (E:annotated (let ((pv2 (E-provenance E))) (if (eq? pv pv2) pv (cons pv pv2)))
                   (if (E:annotated? E) (E:annotated-E E) E))
      E))
